version: '2'
services:
   rabbitmq:
      image: rabbitmq:3
      container_name: rabbitmq

   database:
      build: ./postgres
      container_name: database
      environment:
         - PGPASSWORD=docker
         - POSTGRES_USER=docker
         - POSTGRES_PASSWORD=docker
         - POSTGRES_DB=datamanager

   elasticsearch:
      image: elasticsearch:5.0      
      container_name: elasticsearch
      volumes:
         - ./elasticsearch/config:/usr/share/elasticsearch/config

   tomcat:
      build: ./tomcat
      container_name: tomcat
      ports: 
        - "8889:8080"
      volumes:
        - ./share/log:/usr/local/tomcat/logs/
        - ./share/webapps/KITDM:/KITDM/
      links:
        - database
        - elasticsearch
        - rabbitmq
      environment:
        - ELASTICSEARCH_PORT_9300_TCP_ADDR=elasticsearch
        - DATABASE_PORT_5432_TCP_ADDR=database
        - RABBITMQ_PORT_4369_TCP_ADDR=rabbitmq 
