tomcat:
   build: ./tomcat
   ports: 
     - "8889:8080"
   links:
     - database
     - elasticsearch
database:
   build: ./postgres
   ports:
      - "5432:5432"
elasticsearch:
   build: ./elasticsearch
   ports:
      - "9200:9200"
      - "9300:9300"
